namespace Autodesk.Revit.DB;

public partial class Ellipse : Autodesk.Revit.DB.Curve
{
	public Ellipse() {}
	public static Autodesk.Revit.DB.Curve CreateCurve(Autodesk.Revit.DB.XYZ center,System.Double xRadius,System.Double yRadius,Autodesk.Revit.DB.XYZ xAxis,Autodesk.Revit.DB.XYZ yAxis,System.Double startParameter,System.Double endParameter) => throw new System.NotImplementedException();
	public virtual System.Double RadiusY
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Double RadiusX
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.XYZ YDirection
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.XYZ XDirection
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.XYZ Normal
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.XYZ Center
	{
		get => throw new System.NotImplementedException();
	}
}
