namespace Autodesk.Revit.UI;

public enum SketchGalleryOptions
{
  SGO_Default,
  SGO_Line,
  SGO_Rect,
  SGO_InscribedPolygon,
  SGO_CircumscribedPolygon,
  SGO_Circle,
  SGO_Arc3Point,
  SGO_ArcCenterEnds,
  SGO_ArcTanEnd,
  SGO_ArcFillet,
  SGO_Spline,
  SGO_SplineByPoints,
  SGO_FullEllipse,
  SGO_PartialEllipse,
  SGO_PickLines,
  SGO_PickFaces,
  SGO_PickWalls,
  SGO_PickSupports,
  SGO_PickRoofs,
  SGO_Point,
  SGO_PickPoints,
  SGO_PointElement,
  SGO_RunLine,
  SGO_RunArcFullStep,
  SGO_RunArcCenterEnds,
  SGO_LandingSquare,
  SGO_WinderLShape,
  SGO_WinderPattern,
  SGO_SupportPickLine,
  SGO_WinderUShape,
  SGO_LandingWithTwoRuns,
  SGO_SketchRun,
  SGO_SketchLanding,
}
