namespace Autodesk.Revit.DB;

public partial class GeometryCreationUtilities
{
	public static Autodesk.Revit.DB.Solid CreateExtrusionGeometry(IList<Autodesk.Revit.DB.CurveLoop> profileLoops,Autodesk.Revit.DB.XYZ extrusionDir,System.Double extrusionDist,Autodesk.Revit.DB.SolidOptions solidOptions) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateExtrusionGeometry(IList<Autodesk.Revit.DB.CurveLoop> profileLoops,Autodesk.Revit.DB.XYZ extrusionDir,System.Double extrusionDist) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateRevolvedGeometry(Autodesk.Revit.DB.Frame coordinateFrame,IList<Autodesk.Revit.DB.CurveLoop> profileLoops,System.Double startAngle,System.Double endAngle,Autodesk.Revit.DB.SolidOptions solidOptions) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateRevolvedGeometry(Autodesk.Revit.DB.Frame coordinateFrame,IList<Autodesk.Revit.DB.CurveLoop> profileLoops,System.Double startAngle,System.Double endAngle) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateSweptGeometry(Autodesk.Revit.DB.CurveLoop sweepPath,System.Int32 pathAttachmentCrvIdx,System.Double pathAttachmentParam,IList<Autodesk.Revit.DB.CurveLoop> profileLoops,Autodesk.Revit.DB.SolidOptions solidOptions) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateSweptGeometry(Autodesk.Revit.DB.CurveLoop sweepPath,System.Int32 pathAttachmentCrvIdx,System.Double pathAttachmentParam,IList<Autodesk.Revit.DB.CurveLoop> profileLoops) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateSweptBlendGeometry(Autodesk.Revit.DB.Curve pathCurve,IList<System.Double> pathParams,IList<Autodesk.Revit.DB.CurveLoop> profileLoops,IList<ICollection<Autodesk.Revit.DB.VertexPair>> vertexPairs,Autodesk.Revit.DB.SolidOptions solidOptions) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateSweptBlendGeometry(Autodesk.Revit.DB.Curve pathCurve,IList<System.Double> pathParams,IList<Autodesk.Revit.DB.CurveLoop> profileLoops,IList<ICollection<Autodesk.Revit.DB.VertexPair>> vertexPairs) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateBlendGeometry(Autodesk.Revit.DB.CurveLoop firstLoop,Autodesk.Revit.DB.CurveLoop secondLoop,ICollection<Autodesk.Revit.DB.VertexPair> vertexPairs,Autodesk.Revit.DB.SolidOptions solidOptions) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateBlendGeometry(Autodesk.Revit.DB.CurveLoop firstLoop,Autodesk.Revit.DB.CurveLoop secondLoop,ICollection<Autodesk.Revit.DB.VertexPair> vertexPairs) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateLoftGeometry(IList<Autodesk.Revit.DB.CurveLoop> profileLoops,Autodesk.Revit.DB.SolidOptions solidOptions) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateFixedReferenceSweptGeometry(Autodesk.Revit.DB.CurveLoop sweepPath,System.Int32 pathAttachmentCrvIdx,System.Double pathAttachmentParam,IList<Autodesk.Revit.DB.CurveLoop> profileLoops,Autodesk.Revit.DB.XYZ fixedReferenceDirection,Autodesk.Revit.DB.SolidOptions solidOptions) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateFixedReferenceSweptGeometry(Autodesk.Revit.DB.CurveLoop sweepPath,System.Int32 pathAttachmentCrvIdx,System.Double pathAttachmentParam,IList<Autodesk.Revit.DB.CurveLoop> profileLoops,Autodesk.Revit.DB.XYZ fixedReferenceDirection) => throw new System.NotImplementedException();
}
