namespace Autodesk.Revit.DB.Analysis;

public partial class AnalysisDisplayLegendSettings : System.IDisposable
{
  public AnalysisDisplayLegendSettings() => throw new System.NotImplementedException();

  public AnalysisDisplayLegendSettings(Autodesk.Revit.DB.Analysis.AnalysisDisplayLegendSettings other) =>
    throw new System.NotImplementedException();

  public virtual System.Boolean IsEqual(Autodesk.Revit.DB.Analysis.AnalysisDisplayLegendSettings other) =>
    throw new System.NotImplementedException();

  public virtual void Dispose() => throw new System.NotImplementedException();

  public virtual System.Boolean IsValidObject
  {
    get => throw new System.NotImplementedException();
  }
  public virtual System.Double NumberForScale
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Int32 ScaleHeight
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Int32 ColorRangeHeight
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Int32 ColorRangeWidth
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Int32 NumberOfSteps
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Double Rounding
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Boolean ShowDataDescription
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Boolean ShowDataName
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Boolean ShowUnits
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Boolean ShowLegend
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual Autodesk.Revit.DB.ElementId HeadingTextTypeId
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual Autodesk.Revit.DB.ElementId TextTypeId
  {
    get => throw new System.NotImplementedException();
    set { }
  }
}
