namespace Autodesk.Revit.DB;

public partial class WallSweepInfo : System.Object
{
	public virtual Autodesk.Revit.DB.ElementId get_ProfileId() => throw new System.NotImplementedException();
	public virtual void set_ProfileId(Autodesk.Revit.DB.ElementId profileId) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId get_MaterialId() => throw new System.NotImplementedException();
	public virtual void set_MaterialId(Autodesk.Revit.DB.ElementId materialId) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.WallSide get_WallSide() => throw new System.NotImplementedException();
	public virtual void set_WallSide(Autodesk.Revit.DB.WallSide wallSide) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.WallSweepType get_WallSweepType() => throw new System.NotImplementedException();
	public virtual void set_WallSweepType(Autodesk.Revit.DB.WallSweepType wallSweepType) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.DistanceMeasuredFrom get_DistanceMeasuredFrom() => throw new System.NotImplementedException();
	public virtual void set_DistanceMeasuredFrom(Autodesk.Revit.DB.DistanceMeasuredFrom distanceMeasuredFrom) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.WallSweepOrientation get_WallSweepOrientation() => throw new System.NotImplementedException();
	public virtual void set_WallSweepOrientation(Autodesk.Revit.DB.WallSweepOrientation wallSweepOrientation) => throw new System.NotImplementedException();
	}
