namespace Autodesk.Revit.DB;

public partial class SweptProfile : System.Object
{
	public virtual Autodesk.Revit.DB.Curve GetDrivingCurve() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Profile GetSweptProfile() => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Double EndSetBack
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Double StartSetBack
	{
		get => throw new System.NotImplementedException();
	}
}
