namespace Autodesk.Revit.UI;

public partial class PromptForFamilyInstancePlacementOptions : System.Object
{
	public virtual Autodesk.Revit.UI.SketchGalleryOptions get_SketchGalleryOptions() => throw new System.NotImplementedException();
	public virtual void set_SketchGalleryOptions(Autodesk.Revit.UI.SketchGalleryOptions sketchGalleryOptions) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.UI.FaceBasedPlacementType get_FaceBasedPlacementType() => throw new System.NotImplementedException();
	public virtual void set_FaceBasedPlacementType(Autodesk.Revit.UI.FaceBasedPlacementType faceBasedPlacementType) => throw new System.NotImplementedException();
	}
