namespace Autodesk.Revit.DB;

public partial class ModelCurveArrArray : Autodesk.Revit.DB.APIObject
{
	public virtual void Clear() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ModelCurveArrArrayIterator ForwardIterator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ModelCurveArrArrayIterator ReverseIterator() => throw new System.NotImplementedException();
	public virtual System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();
	public virtual void Append(Autodesk.Revit.DB.ModelCurveArray item) => throw new System.NotImplementedException();
	public virtual void Insert(Autodesk.Revit.DB.ModelCurveArray item,System.Int32 index) => throw new System.NotImplementedException();
	public virtual System.Boolean IsEmpty
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 Size
	{
		get => throw new System.NotImplementedException();
	}
}
