namespace Autodesk.Revit.DB;

public partial class SpatialElementBoundaryOptions : System.Object
{
	public SpatialElementBoundaryOptions() => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.SpatialElementBoundaryLocation SpatialElementBoundaryLocation
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean StoreFreeBoundaryFaces
	{
		get => throw new System.NotImplementedException();
		set {}
	}
}
