namespace Autodesk.Revit.DB;

public partial class ProjectPosition : System.Object
{
	public ProjectPosition(System.Double ew,System.Double ns,System.Double elevation,System.Double angle) => throw new System.NotImplementedException();
	public ProjectPosition(Autodesk.Revit.DB.ProjectPosition other) => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Double Angle
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double Elevation
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double NorthSouth
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double EastWest
	{
		get => throw new System.NotImplementedException();
		set {}
	}
}
