namespace Autodesk.Revit.DB;

public partial class TextElement : Autodesk.Revit.DB.Element
{
	public TextElement() {}
	public static System.Double GetMinimumAllowedWidth(Autodesk.Revit.DB.Document cdda,Autodesk.Revit.DB.ElementId typeId) => throw new System.NotImplementedException();
	public virtual System.Double GetMinimumAllowedWidth() => throw new System.NotImplementedException();
	public static System.Double GetMaximumAllowedWidth(Autodesk.Revit.DB.Document cdda,Autodesk.Revit.DB.ElementId typeId) => throw new System.NotImplementedException();
	public virtual System.Double GetMaximumAllowedWidth() => throw new System.NotImplementedException();
	public virtual System.Boolean IsTextWrappingActive
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Boolean KeepRotatedTextReadable
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.VerticalTextAlignment VerticalAlignment
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.HorizontalTextAlignment HorizontalAlignment
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.String Text
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.XYZ Coord
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double Width
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double Height
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.XYZ UpDirection
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.XYZ BaseDirection
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.TextElementType Symbol
	{
		get => throw new System.NotImplementedException();
	}
}
