namespace Autodesk.Revit.DB;

public partial class TextElement : Autodesk.Revit.DB.Element
{
	public virtual Autodesk.Revit.DB.TextElementType get_Symbol() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_BaseDirection() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_UpDirection() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_Coord() => throw new System.NotImplementedException();
	public virtual void set_Coord(Autodesk.Revit.DB.XYZ position) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.HorizontalTextAlignment get_HorizontalAlignment() => throw new System.NotImplementedException();
	public virtual void set_HorizontalAlignment(Autodesk.Revit.DB.HorizontalTextAlignment alignment) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.VerticalTextAlignment get_VerticalAlignment() => throw new System.NotImplementedException();
	public virtual void set_VerticalAlignment(Autodesk.Revit.DB.VerticalTextAlignment alignment) => throw new System.NotImplementedException();
}
