namespace Autodesk.Revit.DB;

public partial class VertexIndexPairArray : Autodesk.Revit.DB.APIObject
{
	public virtual void Clear() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.VertexIndexPairArrayIterator ForwardIterator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.VertexIndexPairArrayIterator ReverseIterator() => throw new System.NotImplementedException();
	public virtual System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();
	public virtual void Append(Autodesk.Revit.DB.VertexIndexPair item) => throw new System.NotImplementedException();
	public virtual void Insert(Autodesk.Revit.DB.VertexIndexPair item,System.Int32 index) => throw new System.NotImplementedException();
	public virtual System.Boolean IsEmpty
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 Size
	{
		get => throw new System.NotImplementedException();
	}
}
