namespace Autodesk.Revit.DB;

public partial class Outline : System.Object
{
	public virtual Autodesk.Revit.DB.XYZ get_MinimumPoint() => throw new System.NotImplementedException();
	public virtual void set_MinimumPoint(Autodesk.Revit.DB.XYZ minimumPoint) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_MaximumPoint() => throw new System.NotImplementedException();
	public virtual void set_MaximumPoint(Autodesk.Revit.DB.XYZ maximumPoint) => throw new System.NotImplementedException();
	public virtual void AddPoint(Autodesk.Revit.DB.XYZ point) => throw new System.NotImplementedException();
	}
