namespace Autodesk.Revit.DB;

public partial class ViewDisplayModel : System.Object
{
	public virtual Autodesk.Revit.DB.ElementId get_SilhouetteEdgesGStyleId() => throw new System.NotImplementedException();
	public virtual void set_SilhouetteEdgesGStyleId(Autodesk.Revit.DB.ElementId silhouetteEdgesGStyleId) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ShowHiddenLinesValues get_ShowHiddenLines() => throw new System.NotImplementedException();
	public virtual void set_ShowHiddenLines(Autodesk.Revit.DB.ShowHiddenLinesValues ShowHiddenLines) => throw new System.NotImplementedException();
	}
