namespace Autodesk.Revit.DB;

public partial class BRepBuilderSurfaceGeometry : System.Object
{
	public static Autodesk.Revit.DB.BRepBuilderSurfaceGeometry Create(Autodesk.Revit.DB.Surface surface,Autodesk.Revit.DB.BoundingBoxUV surfaceEnvelope) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.BRepBuilderSurfaceGeometry CreateNURBSSurface(System.Int32 degreeU,System.Int32 degreeV,IList<System.Double> knotsU,IList<System.Double> knotsV,IList<Autodesk.Revit.DB.XYZ> controlPoints,IList<System.Double> weights,System.Boolean bReverseOrientation,Autodesk.Revit.DB.BoundingBoxUV surfaceEnvelope) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.BRepBuilderSurfaceGeometry CreateNURBSSurface(System.Int32 degreeU,System.Int32 degreeV,IList<System.Double> knotsU,IList<System.Double> knotsV,IList<Autodesk.Revit.DB.XYZ> controlPoints,System.Boolean bReverseOrientation,Autodesk.Revit.DB.BoundingBoxUV surfaceEnvelope) => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
}
