namespace Autodesk.Revit.DB;

public partial class VertexPair : System.IDisposable
{
  public VertexPair(System.Int32 firstVertexIdx, System.Int32 secondVertexIdx) =>
    throw new System.NotImplementedException();

  public virtual void Dispose() => throw new System.NotImplementedException();

  public virtual System.Boolean IsValidObject
  {
    get => throw new System.NotImplementedException();
  }
  public virtual System.Int32 Second
  {
    get => throw new System.NotImplementedException();
    set { }
  }
  public virtual System.Int32 First
  {
    get => throw new System.NotImplementedException();
    set { }
  }
}
