namespace Autodesk.Revit.DB.Architecture;

public partial class StairsRunType : Autodesk.Revit.DB.ElementType
{
	public virtual Autodesk.Revit.DB.Architecture.StairsUndersideSurfaceStyle get_UndersideSurfaceStyle() => throw new System.NotImplementedException();
	public virtual void set_UndersideSurfaceStyle(Autodesk.Revit.DB.Architecture.StairsUndersideSurfaceStyle undersideSurfaceStyle) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId get_MaterialId() => throw new System.NotImplementedException();
	public virtual void set_MaterialId(Autodesk.Revit.DB.ElementId materialId) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId get_NosingProfile() => throw new System.NotImplementedException();
	public virtual void set_NosingProfile(Autodesk.Revit.DB.ElementId profile) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId get_TreadProfile() => throw new System.NotImplementedException();
	public virtual void set_TreadProfile(Autodesk.Revit.DB.ElementId profile) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Architecture.TreadNosingPosition get_TreadNosingPosition() => throw new System.NotImplementedException();
	public virtual void set_TreadNosingPosition(Autodesk.Revit.DB.Architecture.TreadNosingPosition nosingPosition) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId get_RiserProfile() => throw new System.NotImplementedException();
	public virtual void set_RiserProfile(Autodesk.Revit.DB.ElementId profile) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Architecture.RiserToTreadConnectionOption get_RiserToTreadConnect() => throw new System.NotImplementedException();
	public virtual void set_RiserToTreadConnect(Autodesk.Revit.DB.Architecture.RiserToTreadConnectionOption connect) => throw new System.NotImplementedException();
}
