namespace Autodesk.Revit.DB;

public partial class MEPCurveType : Autodesk.Revit.DB.HostObjAttributes
{
		public virtual Autodesk.Revit.DB.JunctionType get_PreferredJunctionType() => throw new System.NotImplementedException();
	public virtual void set_PreferredJunctionType(Autodesk.Revit.DB.JunctionType junctionType) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_Tee() => throw new System.NotImplementedException();
	public virtual void set_Tee(Autodesk.Revit.DB.FamilySymbol familySymbol) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_Tap() => throw new System.NotImplementedException();
	public virtual void set_Tap(Autodesk.Revit.DB.FamilySymbol familySymbol) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_Transition() => throw new System.NotImplementedException();
	public virtual void set_Transition(Autodesk.Revit.DB.FamilySymbol familySymbol) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_Union() => throw new System.NotImplementedException();
	public virtual void set_Union(Autodesk.Revit.DB.FamilySymbol familySymbol) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_Cross() => throw new System.NotImplementedException();
	public virtual void set_Cross(Autodesk.Revit.DB.FamilySymbol familySymbol) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_Elbow() => throw new System.NotImplementedException();
	public virtual void set_Elbow(Autodesk.Revit.DB.FamilySymbol familySymbol) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_MultiShapeTransition() => throw new System.NotImplementedException();
	public virtual void set_MultiShapeTransition(Autodesk.Revit.DB.FamilySymbol familySymbol) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.RoutingPreferenceManager get_RoutingPreferenceManager() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ConnectorProfileType get_Shape() => throw new System.NotImplementedException();
}
