namespace Autodesk.Revit.DB;

public partial class BeamSystem : Autodesk.Revit.DB.Element
{
	public virtual Autodesk.Revit.DB.Level get_Level() => throw new System.NotImplementedException();
	public virtual void set_Level(Autodesk.Revit.DB.Level level) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilySymbol get_BeamType() => throw new System.NotImplementedException();
	public virtual void set_BeamType(Autodesk.Revit.DB.FamilySymbol pBeamType) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.BeamSystemType get_BeamSystemType() => throw new System.NotImplementedException();
	public virtual void set_BeamSystemType(Autodesk.Revit.DB.BeamSystemType pBeamSystemType) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CurveArray get_Profile() => throw new System.NotImplementedException();
	public virtual void set_Profile(Autodesk.Revit.DB.CurveArray profile) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.LayoutRule get_LayoutRule() => throw new System.NotImplementedException();
	public virtual void set_LayoutRule(Autodesk.Revit.DB.LayoutRule pLayoutRule) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_Direction() => throw new System.NotImplementedException();
}
