namespace Autodesk.Revit.DB;

public partial class BaseImportOptions : System.Object
{
	public virtual Autodesk.Revit.DB.ImportUnit get_Unit() => throw new System.NotImplementedException();
	public virtual void set_Unit(Autodesk.Revit.DB.ImportUnit unit) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ImportColorMode get_ColorMode() => throw new System.NotImplementedException();
	public virtual void set_ColorMode(Autodesk.Revit.DB.ImportColorMode colorMode) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ImportPlacement get_Placement() => throw new System.NotImplementedException();
	public virtual void set_Placement(Autodesk.Revit.DB.ImportPlacement placement) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_ReferencePoint() => throw new System.NotImplementedException();
	public virtual void set_ReferencePoint(Autodesk.Revit.DB.XYZ point) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ForgeTypeId GetDefaultLengthUnit() => throw new System.NotImplementedException();
	public virtual void SetDefaultLengthUnit(Autodesk.Revit.DB.ForgeTypeId specTypeId) => throw new System.NotImplementedException();
	}
