namespace Autodesk.Revit.DB.Architecture;

public partial class StairsLanding : Autodesk.Revit.DB.Element
{
	public virtual Autodesk.Revit.DB.CurveLoop GetFootprintBoundary() => throw new System.NotImplementedException();
	public virtual void SetSketchedLandingBoundaryAndPath(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.CurveLoop boundaryCurveLoop,Autodesk.Revit.DB.CurveLoop pathCurveLoop) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Architecture.Stairs GetStairs() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CurveLoop GetStairsPath() => throw new System.NotImplementedException();
}
