namespace Autodesk.Revit.DB;

public partial class CurveByPointsUtils : System.IDisposable
{
	public static Autodesk.Revit.DB.CurveProjectionType GetProjectionType(Autodesk.Revit.DB.CurveElement curveElem) => throw new System.NotImplementedException();
	public static void SetProjectionType(Autodesk.Revit.DB.CurveElement curveElem,Autodesk.Revit.DB.CurveProjectionType value) => throw new System.NotImplementedException();
	public static System.Boolean GetSketchOnSurface(Autodesk.Revit.DB.CurveElement curveElem) => throw new System.NotImplementedException();
	public static void SetSketchOnSurface(Autodesk.Revit.DB.CurveElement curveElem,System.Boolean sketchOnSurface) => throw new System.NotImplementedException();
	public static System.Boolean ValidateCurveElementIdArrayForFaceRegions(Autodesk.Revit.DB.Document document,IList<Autodesk.Revit.DB.ElementId> curveElemIds) => throw new System.NotImplementedException();
	public static void AddCurvesToFaceRegion(Autodesk.Revit.DB.Document document,IList<Autodesk.Revit.DB.ElementId> curveElemIds) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Reference GetHostFace(Autodesk.Revit.DB.CurveElement curveElem) => throw new System.NotImplementedException();
	public static IList<Autodesk.Revit.DB.Reference> GetFaceRegions(Autodesk.Revit.DB.Document cda,Autodesk.Revit.DB.Reference referenceOfFace) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.CurveElement CreateArcThroughPoints(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ReferencePoint startPoint,Autodesk.Revit.DB.ReferencePoint endPoint,Autodesk.Revit.DB.ReferencePoint interiorPoint) => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
}
