namespace Autodesk.Revit.DB;

public partial class JoinGeometryUtils
{
	public JoinGeometryUtils() {}
	public static void JoinGeometry(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element firstElement,Autodesk.Revit.DB.Element secondElement) => throw new System.NotImplementedException();
	public static void UnjoinGeometry(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element firstElement,Autodesk.Revit.DB.Element secondElement) => throw new System.NotImplementedException();
	public static void SwitchJoinOrder(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element firstElement,Autodesk.Revit.DB.Element secondElement) => throw new System.NotImplementedException();
	public static System.Boolean AreElementsJoined(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element firstElement,Autodesk.Revit.DB.Element secondElement) => throw new System.NotImplementedException();
	public static System.Boolean IsCuttingElementInJoin(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element firstElement,Autodesk.Revit.DB.Element secondElement) => throw new System.NotImplementedException();
	public static System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> GetJoinedElements(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element element) => throw new System.NotImplementedException();
}
