namespace Autodesk.Revit.DB;

public partial class ElementRecord : System.Object
{
	public virtual Autodesk.Revit.DB.ElementId GetId() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId GetCategoryId() => throw new System.NotImplementedException();
	public virtual System.Boolean IsAnElementType() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId GetOwnerViewId() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId GetDesignOptionId() => throw new System.NotImplementedException();
	public virtual System.Boolean IsCurveDriven() => throw new System.NotImplementedException();
	public virtual System.Boolean HasBoundingBox() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Outline GetBoundingBox() => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.WorksetId WorksetId
	{
		get => throw new System.NotImplementedException();
	}
}
