namespace Autodesk.Revit.DB;

public partial class CompoundStructure : System.Object
{
	public virtual Autodesk.Revit.DB.EndCapCondition get_EndCap() => throw new System.NotImplementedException();
	public virtual void set_EndCap(Autodesk.Revit.DB.EndCapCondition endCap) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.OpeningWrappingCondition get_OpeningWrapping() => throw new System.NotImplementedException();
	public virtual void set_OpeningWrapping(Autodesk.Revit.DB.OpeningWrappingCondition wrapping) => throw new System.NotImplementedException();
	public virtual void AddWallSweep(Autodesk.Revit.DB.WallSweepInfo wallSweepInfo) => throw new System.NotImplementedException();
	public virtual void ClearWallSweeps(Autodesk.Revit.DB.WallSweepType wallSweepType) => throw new System.NotImplementedException();
	}
