namespace Autodesk.Revit.DB;

public partial class SolidUtils : System.Object
{
	public static Autodesk.Revit.DB.Solid Clone(Autodesk.Revit.DB.Solid solid) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Solid CreateTransformed(Autodesk.Revit.DB.Solid solid,Autodesk.Revit.DB.Transform transform) => throw new System.NotImplementedException();
	public static IList<Autodesk.Revit.DB.Solid> SplitVolumes(Autodesk.Revit.DB.Solid solid) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.TriangulatedSolidOrShell TessellateSolidOrShell(Autodesk.Revit.DB.Solid solidOrShell,Autodesk.Revit.DB.SolidOrShellTessellationControls tessellationControls) => throw new System.NotImplementedException();
	public static System.Boolean IsValidForTessellation(Autodesk.Revit.DB.Solid solidOrShell) => throw new System.NotImplementedException();
	public static IList<Autodesk.Revit.DB.EdgeEndPoint> FindAllEdgeEndPointsAtVertex(Autodesk.Revit.DB.EdgeEndPoint edgeEndPoint) => throw new System.NotImplementedException();
}
