namespace Autodesk.Revit.DB;

public partial class CurveByPointsArray : Autodesk.Revit.DB.APIObject,System.Collections.IEnumerable
{
	public CurveByPointsArray() {}
	public virtual void Clear() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CurveByPointsArrayIterator ForwardIterator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CurveByPointsArrayIterator ReverseIterator() => throw new System.NotImplementedException();
	public virtual System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CurveByPoints get_Item(System.Int32 index) => throw new System.NotImplementedException();
	public virtual void set_Item(System.Int32 index,Autodesk.Revit.DB.CurveByPoints item) => throw new System.NotImplementedException();
	public virtual void Append(Autodesk.Revit.DB.CurveByPoints item) => throw new System.NotImplementedException();
	public virtual void Insert(Autodesk.Revit.DB.CurveByPoints item,System.Int32 index) => throw new System.NotImplementedException();
	public virtual System.Boolean IsEmpty
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 Size
	{
		get => throw new System.NotImplementedException();
	}
}
