namespace Autodesk.Revit.DB;

public partial class SpatialElementTag : Autodesk.Revit.DB.Element
{
		public virtual Autodesk.Revit.DB.SpatialElementTagOrientation get_TagOrientation() => throw new System.NotImplementedException();
	public virtual void set_TagOrientation(Autodesk.Revit.DB.SpatialElementTagOrientation orientation) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_TagHeadPosition() => throw new System.NotImplementedException();
	public virtual void set_TagHeadPosition(Autodesk.Revit.DB.XYZ point) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_LeaderEnd() => throw new System.NotImplementedException();
	public virtual void set_LeaderEnd(Autodesk.Revit.DB.XYZ point) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_LeaderElbow() => throw new System.NotImplementedException();
	public virtual void set_LeaderElbow(Autodesk.Revit.DB.XYZ point) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.View get_View() => throw new System.NotImplementedException();
}
