namespace Autodesk.Revit.DB;

public partial class ModelCurveArray : Autodesk.Revit.DB.APIObject,System.Collections.IEnumerable
{
	public ModelCurveArray() => throw new System.NotImplementedException();
	public virtual void Clear() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ModelCurveArrayIterator ForwardIterator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ModelCurveArrayIterator ReverseIterator() => throw new System.NotImplementedException();
	public virtual System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();
	public virtual void Append(Autodesk.Revit.DB.ModelCurve item) => throw new System.NotImplementedException();
	public virtual void Insert(Autodesk.Revit.DB.ModelCurve item,System.Int32 index) => throw new System.NotImplementedException();
	public virtual System.Boolean IsEmpty
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 Size
	{
		get => throw new System.NotImplementedException();
	}
}
