namespace Autodesk.Revit.DB;

public partial class ACADExportOptions : Autodesk.Revit.DB.BaseExportOptions
{
	public virtual Autodesk.Revit.DB.LineScaling get_LineScaling() => throw new System.NotImplementedException();
	public virtual void set_LineScaling(Autodesk.Revit.DB.LineScaling lineScaling) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.TextTreatment get_TextTreatment() => throw new System.NotImplementedException();
	public virtual void set_TextTreatment(Autodesk.Revit.DB.TextTreatment textTreatment) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.SolidGeometry get_ExportOfSolids() => throw new System.NotImplementedException();
	public virtual void set_ExportOfSolids(Autodesk.Revit.DB.SolidGeometry exportOfSolids) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ACAObjectPreference get_ACAPreference() => throw new System.NotImplementedException();
	public virtual void set_ACAPreference(Autodesk.Revit.DB.ACAObjectPreference aCAPreference) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ExportUnit get_TargetUnit() => throw new System.NotImplementedException();
	public virtual void set_TargetUnit(Autodesk.Revit.DB.ExportUnit targetUnit) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ACADVersion get_FileVersion() => throw new System.NotImplementedException();
	public virtual void set_FileVersion(Autodesk.Revit.DB.ACADVersion fileVersion) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Color get_HatchBackgroundColor() => throw new System.NotImplementedException();
	public virtual void set_HatchBackgroundColor(Autodesk.Revit.DB.Color hatchBackgroundColor) => throw new System.NotImplementedException();
}
