namespace Autodesk.Revit.DB;

public partial class PartMakerMethodToDivideVolumes : System.Object
{
	public virtual Autodesk.Revit.DB.PartEdgeConditionOrientation get_ProfileMatch() => throw new System.NotImplementedException();
	public virtual void set_ProfileMatch(Autodesk.Revit.DB.PartEdgeConditionOrientation profileMatch) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId get_ProfileType() => throw new System.NotImplementedException();
	public virtual void set_ProfileType(Autodesk.Revit.DB.ElementId profileType) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId get_DivisionRuleId() => throw new System.NotImplementedException();
	public virtual void set_DivisionRuleId(Autodesk.Revit.DB.ElementId divisionRuleId) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Plane GetPlaneOfSketch() => throw new System.NotImplementedException();
	}
