namespace Autodesk.Revit.DB;

public partial class FootPrintRoof : Autodesk.Revit.DB.RoofBase
{
  public virtual System.Boolean get_DefinesSlope(Autodesk.Revit.DB.ModelCurve pCurve) =>
    throw new System.NotImplementedException();

  public virtual void set_DefinesSlope(Autodesk.Revit.DB.ModelCurve pCurve, System.Boolean definesSlope) =>
    throw new System.NotImplementedException();

  public virtual System.Double get_SlopeAngle(Autodesk.Revit.DB.ModelCurve pCurve) =>
    throw new System.NotImplementedException();

  public virtual void set_SlopeAngle(Autodesk.Revit.DB.ModelCurve pCurve, System.Double slopeAngle) =>
    throw new System.NotImplementedException();

  public virtual System.Double get_Offset(Autodesk.Revit.DB.ModelCurve pCurve) =>
    throw new System.NotImplementedException();

  public virtual void set_Offset(Autodesk.Revit.DB.ModelCurve pCurve, System.Double offsetValue) =>
    throw new System.NotImplementedException();

  public virtual System.Boolean get_ExtendIntoWall(Autodesk.Revit.DB.ModelCurve pCurve) =>
    throw new System.NotImplementedException();

  public virtual void set_ExtendIntoWall(Autodesk.Revit.DB.ModelCurve pCurve, System.Boolean extendIntoWall) =>
    throw new System.NotImplementedException();

  public virtual System.Double get_Overhang(Autodesk.Revit.DB.ModelCurve pCurve) =>
    throw new System.NotImplementedException();

  public virtual void set_Overhang(Autodesk.Revit.DB.ModelCurve pCurve, System.Double overhangValue) =>
    throw new System.NotImplementedException();

  public virtual Autodesk.Revit.DB.ModelCurveArrArray GetProfiles() => throw new System.NotImplementedException();

  public virtual Autodesk.Revit.DB.CurtainGridSet CurtainGrids
  {
    get => throw new System.NotImplementedException();
  }
}
