namespace Autodesk.Revit.DB.Architecture;

public partial class PostPattern : System.Object
{
	public virtual Autodesk.Revit.DB.Architecture.BalusterInfo get_StartPost() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Architecture.BalusterInfo get_EndPost() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Architecture.BalusterInfo get_CornerPost() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Architecture.BreakCornerCondition get_CornerPostCondition() => throw new System.NotImplementedException();
	public virtual void set_CornerPostCondition(Autodesk.Revit.DB.Architecture.BreakCornerCondition cornerPostCondition) => throw new System.NotImplementedException();
	}
