namespace Autodesk.Revit.DB;

public partial class SlabShapeVertexArray : Autodesk.Revit.DB.APIObject,System.Collections.IEnumerable
{
	public SlabShapeVertexArray() => throw new System.NotImplementedException();
	public virtual void Clear() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.SlabShapeVertexArrayIterator ForwardIterator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.SlabShapeVertexArrayIterator ReverseIterator() => throw new System.NotImplementedException();
	public virtual System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.SlabShapeVertex get_Item(System.Int32 index) => throw new System.NotImplementedException();
	public virtual void set_Item(System.Int32 index,Autodesk.Revit.DB.SlabShapeVertex item) => throw new System.NotImplementedException();
	public virtual void Append(Autodesk.Revit.DB.SlabShapeVertex item) => throw new System.NotImplementedException();
	public virtual void Insert(Autodesk.Revit.DB.SlabShapeVertex item,System.Int32 index) => throw new System.NotImplementedException();
	public virtual System.Boolean IsEmpty
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 Size
	{
		get => throw new System.NotImplementedException();
	}
}
