namespace Autodesk.Revit.DB;

public partial class PlanViewRange : System.Object
{
	public virtual Autodesk.Revit.DB.ElementId GetLevelId(Autodesk.Revit.DB.PlanViewPlane planViewPlane) => throw new System.NotImplementedException();
	public virtual void SetLevelId(Autodesk.Revit.DB.PlanViewPlane planViewPlane,Autodesk.Revit.DB.ElementId id) => throw new System.NotImplementedException();
	public virtual System.Double GetOffset(Autodesk.Revit.DB.PlanViewPlane planViewPlane) => throw new System.NotImplementedException();
	public virtual void SetOffset(Autodesk.Revit.DB.PlanViewPlane planViewPlane,System.Double offset) => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public static  Autodesk.Revit.DB.ElementId Current
	{
		get => throw new System.NotImplementedException();
	}
	public static  Autodesk.Revit.DB.ElementId LevelBelow
	{
		get => throw new System.NotImplementedException();
	}
	public static  Autodesk.Revit.DB.ElementId LevelAbove
	{
		get => throw new System.NotImplementedException();
	}
	public static  Autodesk.Revit.DB.ElementId Unlimited
	{
		get => throw new System.NotImplementedException();
	}
}
