namespace Autodesk.Revit.DB;

public partial class SlabShapeCreaseArray : Autodesk.Revit.DB.APIObject, System.Collections.IEnumerable
{
  public SlabShapeCreaseArray() => throw new System.NotImplementedException();

  public virtual void Clear() => throw new System.NotImplementedException();

  public virtual Autodesk.Revit.DB.SlabShapeCreaseArrayIterator ForwardIterator() =>
    throw new System.NotImplementedException();

  public virtual Autodesk.Revit.DB.SlabShapeCreaseArrayIterator ReverseIterator() =>
    throw new System.NotImplementedException();

  public virtual System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();

  public virtual Autodesk.Revit.DB.SlabShapeCrease get_Item(System.Int32 index) =>
    throw new System.NotImplementedException();

  public virtual void set_Item(System.Int32 index, Autodesk.Revit.DB.SlabShapeCrease item) =>
    throw new System.NotImplementedException();

  public virtual void Append(Autodesk.Revit.DB.SlabShapeCrease item) => throw new System.NotImplementedException();

  public virtual void Insert(Autodesk.Revit.DB.SlabShapeCrease item, System.Int32 index) =>
    throw new System.NotImplementedException();

  public virtual System.Boolean IsEmpty
  {
    get => throw new System.NotImplementedException();
  }
  public virtual System.Int32 Size
  {
    get => throw new System.NotImplementedException();
  }
}
