namespace Autodesk.Revit.DB;

public partial class CurveByPoints : Autodesk.Revit.DB.CurveElement
{
			public virtual Autodesk.Revit.DB.ReferencePointArray GetPoints() => throw new System.NotImplementedException();
	public virtual void SetPoints(Autodesk.Revit.DB.ReferencePointArray points) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilyElementVisibility GetVisibility() => throw new System.NotImplementedException();
	public virtual void SetVisibility(Autodesk.Revit.DB.FamilyElementVisibility visibility) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.GraphicsStyle get_Subcategory() => throw new System.NotImplementedException();
	public virtual void set_Subcategory(Autodesk.Revit.DB.GraphicsStyle subcategory) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ReferenceType get_ReferenceType() => throw new System.NotImplementedException();
	public virtual void set_ReferenceType(Autodesk.Revit.DB.ReferenceType referenceType) => throw new System.NotImplementedException();
}
