namespace Autodesk.Revit.DB;

public partial class ReferencePoint : Autodesk.Revit.DB.Element
{
			public virtual Autodesk.Revit.DB.PointElementReference GetPointElementReference() => throw new System.NotImplementedException();
	public virtual void SetPointElementReference(Autodesk.Revit.DB.PointElementReference pointElementReference) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Transform GetCoordinateSystem() => throw new System.NotImplementedException();
	public virtual void SetCoordinateSystem(Autodesk.Revit.DB.Transform coordinateSystem) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.XYZ get_Position() => throw new System.NotImplementedException();
	public virtual void set_Position(Autodesk.Revit.DB.XYZ A_0) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CurveByPointsArray GetInterpolatingCurves() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Reference GetCoordinatePlaneReferenceXY() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Reference GetCoordinatePlaneReferenceYZ() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Reference GetCoordinatePlaneReferenceXZ() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.FamilyElementVisibility GetVisibility() => throw new System.NotImplementedException();
	public virtual void SetVisibility(Autodesk.Revit.DB.FamilyElementVisibility visibility) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.ElementId GetHubId() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CoordinatePlaneVisibility get_CoordinatePlaneVisibility() => throw new System.NotImplementedException();
	public virtual void set_CoordinatePlaneVisibility(Autodesk.Revit.DB.CoordinatePlaneVisibility A_0) => throw new System.NotImplementedException();
}
