namespace Autodesk.Revit.DB;

public partial class BeamSystem : Autodesk.Revit.DB.Element
{
	public virtual Autodesk.Revit.DB.XYZ Direction
	{
		get => throw new System.NotImplementedException();
	}
	public virtual Autodesk.Revit.DB.LayoutRule LayoutRule
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.CurveArray Profile
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.BeamSystemType BeamSystemType
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.FamilySymbol BeamType
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Level Level
	{
		get => throw new System.NotImplementedException();
		set {}
	}
}
