namespace Autodesk.Revit.DB.Mechanical;

public partial class MechanicalUtils
{
	public static System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> ConvertDuctPlaceholders(Autodesk.Revit.DB.Document document,System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> placeholderIds) => throw new System.NotImplementedException();
	public static System.Boolean ConnectDuctPlaceholdersAtElbow(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Connector connector1,Autodesk.Revit.DB.Connector connector2) => throw new System.NotImplementedException();
	public static System.Boolean ConnectDuctPlaceholdersAtElbow(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ElementId placeholder1Id,Autodesk.Revit.DB.ElementId placeholder2Id) => throw new System.NotImplementedException();
	public static System.Boolean ConnectDuctPlaceholdersAtTee(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Connector connector1,Autodesk.Revit.DB.Connector connector2,Autodesk.Revit.DB.Connector connector3) => throw new System.NotImplementedException();
	public static System.Boolean ConnectDuctPlaceholdersAtTee(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ElementId placeholder1Id,Autodesk.Revit.DB.ElementId placeholder2Id) => throw new System.NotImplementedException();
	public static System.Boolean ConnectDuctPlaceholdersAtCross(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Connector connector1,Autodesk.Revit.DB.Connector connector2,Autodesk.Revit.DB.Connector connector3,Autodesk.Revit.DB.Connector connector4) => throw new System.NotImplementedException();
	public static System.Boolean ConnectDuctPlaceholdersAtCross(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ElementId placeholder1Id,Autodesk.Revit.DB.ElementId placeholder2Id,Autodesk.Revit.DB.ElementId placeholder3Id) => throw new System.NotImplementedException();
	public static System.Boolean ConnectDuctPlaceholdersAtCross(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ElementId placeholder1Id,Autodesk.Revit.DB.ElementId placeholder2Id) => throw new System.NotImplementedException();
	public static System.Boolean ConnectAirTerminalOnDuct(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ElementId airTerminalId,Autodesk.Revit.DB.ElementId ductCurveId) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.ElementId BreakCurve(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ElementId ductId,Autodesk.Revit.DB.XYZ ptBreak) => throw new System.NotImplementedException();
}
