namespace Autodesk.Revit.DB.Mechanical;

public partial class MEPHiddenLineSettings : Autodesk.Revit.DB.Element
{
	public MEPHiddenLineSettings() {}
	public static Autodesk.Revit.DB.Mechanical.MEPHiddenLineSettings GetMEPHiddenLineSettings(Autodesk.Revit.DB.Document doc) => throw new System.NotImplementedException();
	public virtual System.Boolean DrawHiddenLine
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.ElementId LineStyle
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double SingleLineGap
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double OutsideGap
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double InsideGap
	{
		get => throw new System.NotImplementedException();
		set {}
	}
}
