namespace Autodesk.Revit.DB;

public partial class InstanceVoidCutUtils : System.Object
{
	public static System.Boolean CanBeCutWithVoid(Autodesk.Revit.DB.Element element) => throw new System.NotImplementedException();
	public static System.Boolean IsVoidInstanceCuttingElement(Autodesk.Revit.DB.Element element) => throw new System.NotImplementedException();
	public static void AddInstanceVoidCut(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element element,Autodesk.Revit.DB.Element cuttingInstance) => throw new System.NotImplementedException();
	public static void RemoveInstanceVoidCut(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.Element element,Autodesk.Revit.DB.Element cuttingInstance) => throw new System.NotImplementedException();
	public static System.Boolean InstanceVoidCutExists(Autodesk.Revit.DB.Element element,Autodesk.Revit.DB.Element cuttingInstance) => throw new System.NotImplementedException();
	public static ICollection<Autodesk.Revit.DB.ElementId> GetElementsBeingCut(Autodesk.Revit.DB.Element cuttingInstance) => throw new System.NotImplementedException();
	public static ICollection<Autodesk.Revit.DB.ElementId> GetCuttingVoidInstances(Autodesk.Revit.DB.Element element) => throw new System.NotImplementedException();
}
