namespace Autodesk.Revit.UI;

public partial class ExternalApplicationArray : Autodesk.Revit.DB.APIObject,System.Collections.IEnumerable
{
	public ExternalApplicationArray() => throw new System.NotImplementedException();
	public virtual void Clear() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.UI.ExternalApplicationArrayIterator ForwardIterator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.UI.ExternalApplicationArrayIterator ReverseIterator() => throw new System.NotImplementedException();
	public virtual System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.UI.IExternalApplication get_Item(System.Int32 index) => throw new System.NotImplementedException();
	public virtual void set_Item(System.Int32 index,Autodesk.Revit.UI.IExternalApplication item) => throw new System.NotImplementedException();
	public virtual void Append(Autodesk.Revit.UI.IExternalApplication item) => throw new System.NotImplementedException();
	public virtual void Insert(Autodesk.Revit.UI.IExternalApplication item,System.Int32 index) => throw new System.NotImplementedException();
	public virtual System.Boolean IsEmpty
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 Size
	{
		get => throw new System.NotImplementedException();
	}
}
