namespace Autodesk.Revit.DB;

public partial class CurveLoop : System.Object
{
	public virtual void Append(Autodesk.Revit.DB.Curve curve) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.Plane GetPlane() => throw new System.NotImplementedException();
	public virtual void Transform(Autodesk.Revit.DB.Transform transform) => throw new System.NotImplementedException();
	public virtual void Flip() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.CurveLoopIterator GetCurveLoopIterator() => throw new System.NotImplementedException();
		}
