namespace Autodesk.Revit.DB;

public partial class AdaptiveComponentInstanceUtils
{
	public static System.Boolean IsAdaptiveFamilySymbol(Autodesk.Revit.DB.FamilySymbol famSymb) => throw new System.NotImplementedException();
	public static System.Boolean HasAdaptiveFamilySymbol(Autodesk.Revit.DB.FamilyInstance famInst) => throw new System.NotImplementedException();
	public static System.Boolean IsAdaptiveComponentInstance(Autodesk.Revit.DB.FamilyInstance famInst) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.FamilyInstance CreateAdaptiveComponentInstance(Autodesk.Revit.DB.Document doc,Autodesk.Revit.DB.FamilySymbol famSymb) => throw new System.NotImplementedException();
	public static void MoveAdaptiveComponentInstance(Autodesk.Revit.DB.FamilyInstance famInst,Autodesk.Revit.DB.Transform trf,System.Boolean unHost) => throw new System.NotImplementedException();
	public static System.Collections.Generic.IList<Autodesk.Revit.DB.ElementId> GetInstancePointElementRefIds(Autodesk.Revit.DB.FamilyInstance famInst) => throw new System.NotImplementedException();
	public static System.Collections.Generic.IList<Autodesk.Revit.DB.ElementId> GetInstancePlacementPointElementRefIds(Autodesk.Revit.DB.FamilyInstance famInst) => throw new System.NotImplementedException();
	public static System.Collections.Generic.IList<Autodesk.Revit.DB.ElementId> GetInstanceShapeHandlePointElementRefIds(Autodesk.Revit.DB.FamilyInstance famInst) => throw new System.NotImplementedException();
	public static System.Boolean IsInstanceFlipped(Autodesk.Revit.DB.FamilyInstance famInst) => throw new System.NotImplementedException();
	public static void SetInstanceFlipped(Autodesk.Revit.DB.FamilyInstance famInst,System.Boolean flip) => throw new System.NotImplementedException();
}
