namespace Autodesk.Revit.DB;

public partial class PolymeshFacet
{
	public PolymeshFacet(System.Int32 v1,System.Int32 v2,System.Int32 v3) => throw new System.NotImplementedException();
	public virtual IList<System.Int32> GetVertices() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 V3
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 V2
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Int32 V1
	{
		get => throw new System.NotImplementedException();
	}
}
