namespace Autodesk.Revit.DB;

public partial class UV : System.Object
{
	public UV(System.Double u,System.Double v) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.UV Normalize() => throw new System.NotImplementedException();
	public virtual System.Double GetLength() => throw new System.NotImplementedException();
	public virtual System.Boolean IsZeroLength() => throw new System.NotImplementedException();
	public virtual System.Boolean IsUnitLength() => throw new System.NotImplementedException();
	public virtual System.Double DotProduct(Autodesk.Revit.DB.UV source) => throw new System.NotImplementedException();
	public virtual System.Double CrossProduct(Autodesk.Revit.DB.UV source) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.UV Add(Autodesk.Revit.DB.UV source) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.UV Subtract(Autodesk.Revit.DB.UV source) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.UV Negate() => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.UV Multiply(System.Double value) => throw new System.NotImplementedException();
	public virtual Autodesk.Revit.DB.UV Divide(System.Double value) => throw new System.NotImplementedException();
	public virtual System.Boolean IsAlmostEqualTo(Autodesk.Revit.DB.UV source,System.Double tolerance) => throw new System.NotImplementedException();
	public virtual System.Boolean IsAlmostEqualTo(Autodesk.Revit.DB.UV source) => throw new System.NotImplementedException();
	public virtual System.Double DistanceTo(Autodesk.Revit.DB.UV source) => throw new System.NotImplementedException();
	public virtual System.Double AngleTo(Autodesk.Revit.DB.UV source) => throw new System.NotImplementedException();
	public static  Autodesk.Revit.DB.UV BasisV
	{
		get => throw new System.NotImplementedException();
	}
	public static  Autodesk.Revit.DB.UV BasisU
	{
		get => throw new System.NotImplementedException();
	}
	public static  Autodesk.Revit.DB.UV Zero
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Double V
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Double U
	{
		get => throw new System.NotImplementedException();
	}
}
