namespace Autodesk.Revit.DB;

public partial class NavisworksExportOptions : System.IDisposable
{
	public NavisworksExportOptions() => throw new System.NotImplementedException();
	public virtual System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> GetSelectedElementIds() => throw new System.NotImplementedException();
	public virtual void SetSelectedElementIds(System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> ids) => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Boolean ConvertLinkedCADFormats
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ConvertLights
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double FacetingFactor
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean DivideFileIntoLevels
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ConvertElementProperties
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean FindMissingMaterials
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ExportRoomGeometry
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.ElementId ViewId
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.NavisworksExportScope ExportScope
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.NavisworksCoordinates Coordinates
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ExportUrls
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ExportRoomAsAttribute
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ExportLinks
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.NavisworksParameters Parameters
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ExportElementIds
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean ExportParts
	{
		get => throw new System.NotImplementedException();
		set {}
	}
}
