namespace Autodesk.Revit.DB.Structure;

public partial class BendingDetailCustomFieldProperties : Autodesk.Revit.DB.ICustomFieldProperties,System.IDisposable
{
	public BendingDetailCustomFieldProperties() {}
	public virtual System.Boolean AreEqualTo(Autodesk.Revit.DB.ICustomFieldProperties otherProperties) => throw new System.NotImplementedException();
	public virtual void Dispose() => throw new System.NotImplementedException();
	public virtual System.Boolean IsValidObject
	{
		get => throw new System.NotImplementedException();
	}
	public virtual System.Boolean BendDiameterDimensionsForSegmentsEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean BendDiameterDimensionsForHooksEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailBendDiameterDimensionType BendDiameterDimensionType
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean BendDiameterDimensionsEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.ElementId DiameterDimensionTypeId
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.ElementId RadialDimensionTypeId
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailAngularDimensionsMeasurementOptions AngularDimensionsMeasurementOptions
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double AngularDimensionsOffset
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean AngularDimensionsForHooksEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailAngularDimensionsDisplayOptions AngularDimensionsDisplayOption
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailDimensionTextPosition AngularDimensionTextPosition
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean AngularDimensionsEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.ElementId AngularDimensionTypeId
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean OrthogonalAndOverallDimesionsEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailSegmentLengthsDisplayOptions SegmentLengthsForArcsDisplayOption
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailSegmentLengthsDisplayOptions SegmentLengthsDisplayOption
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailDimensionTextPosition SegmentLengthDimensionTextPosition
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Double SegmentLengthDimensionsOffset
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean SegmentLengthDimensionsForHooksEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual System.Boolean SegmentLengthDimensionsEnabled
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.ElementId SegmentLengthDimensionTypeId
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailCustomFieldMultipleValuesIndicatorOptions MultipleValuesIndicatorOption
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailFor3DShapesOptions RepresentaionOf3DShapes
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailSegmentsRepresentation SegmentsRepresentation
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.Structure.BendingDetailDisplayParametersOptions ParametersDisplayOption
	{
		get => throw new System.NotImplementedException();
		set {}
	}
	public virtual Autodesk.Revit.DB.ElementId LineStyleId
	{
		get => throw new System.NotImplementedException();
		set {}
	}
}
