namespace Autodesk.Revit.DB;

public partial class DetailElementOrderUtils
{
	public DetailElementOrderUtils() {}
	public static void BringToFront(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> detailElementIds) => throw new System.NotImplementedException();
	public static void BringToFront(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,Autodesk.Revit.DB.ElementId detailElementId) => throw new System.NotImplementedException();
	public static void BringForward(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> detailElementIds) => throw new System.NotImplementedException();
	public static void BringForward(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,Autodesk.Revit.DB.ElementId detailElementId) => throw new System.NotImplementedException();
	public static void SendToBack(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> detailElementIds) => throw new System.NotImplementedException();
	public static void SendToBack(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,Autodesk.Revit.DB.ElementId detailElementId) => throw new System.NotImplementedException();
	public static void SendBackward(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> detailElementIds) => throw new System.NotImplementedException();
	public static void SendBackward(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,Autodesk.Revit.DB.ElementId detailElementId) => throw new System.NotImplementedException();
	public static System.Collections.Generic.IList<Autodesk.Revit.DB.ElementId> GetDrawOrderForDetails(Autodesk.Revit.DB.View view,System.Collections.Generic.ISet<Autodesk.Revit.DB.ElementId> detailIdsToSort) => throw new System.NotImplementedException();
	public static System.Boolean IsDetailElement(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,Autodesk.Revit.DB.ElementId detailElementId) => throw new System.NotImplementedException();
	public static System.Boolean AreDetailElements(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.View view,System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> detailElementIds) => throw new System.NotImplementedException();
}
