namespace Autodesk.Revit.DB.Structure;

public partial class RebarBendingDetail
{
	public RebarBendingDetail() {}
	public static Autodesk.Revit.DB.Element Create(Autodesk.Revit.DB.Document document,Autodesk.Revit.DB.ElementId viewId,Autodesk.Revit.DB.ElementId reinforcementElementId,System.Int32 reinforcementElementSubelementKey,Autodesk.Revit.DB.Structure.RebarBendingDetailType bendingDetailType,Autodesk.Revit.DB.XYZ position,System.Double rotation) => throw new System.NotImplementedException();
	public static void SetHost(Autodesk.Revit.DB.Element bendingDetail,Autodesk.Revit.DB.Reference reference) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.Reference GetHost(Autodesk.Revit.DB.Element bendingDetail) => throw new System.NotImplementedException();
	public static Autodesk.Revit.DB.XYZ GetPosition(Autodesk.Revit.DB.Element bendingDetail) => throw new System.NotImplementedException();
	public static System.Double GetRotation(Autodesk.Revit.DB.Element bendingDetail) => throw new System.NotImplementedException();
	public static void SetPosition(Autodesk.Revit.DB.Element bendingDetail,Autodesk.Revit.DB.XYZ position) => throw new System.NotImplementedException();
	public static void SetRotation(Autodesk.Revit.DB.Element bendingDetail,System.Double rotation) => throw new System.NotImplementedException();
	public static System.Boolean IsBendingDetail(Autodesk.Revit.DB.Element bendingDetail) => throw new System.NotImplementedException();
}
